data_file: data/b2b_or_b2c.csv
description: Classify if a company is B2B or B2C
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: segment
  from: prediction
- field: score
  from: probability
report_template: '### {url}

  - **Segment**: {segment}

  - **Score**: {score:.2f}%'
task_name: b2b_or_b2c
type: classification
vectorizer: tfidf
