data_file: data/sentiment_analysis.csv
description: Classify sentiment of the content
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: sentiment
  from: prediction
- field: confidence
  from: probability
report_template: '### {url}

  - **Sentiment**: {sentiment}

  - **Confidence**: {confidence:.2f}%'
task_name: sentiment_analysis
type: classification
vectorizer: tfidf
