data_file: data/sentiment_analysis.csv
description: Analiza sentymentu tekstu
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: sentyment
  from: prediction
- field: pewnosc
  from: probability
report_template: '### {url}

  - **Sentyment**: {sentyment}

  - **Pewność**: {pewnosc:.2f}%'
task_name: sentiment_analysis
type: classification
vectorizer: tfidf
