task_name: analiza_nastroju
description: Analiza sentymentu tekstu
type: classification

input_column: content
output_column: label

model: LogisticRegression
vectorizer: tfidf

data_file: data/analiza_nastroju.csv

raw_fields:
  page.url: url
  prediction: sentyment
  probability: pewnosc
  keywords: slowa

template_vars:
  url: url
  sentyment: sentyment
  pewnosc: pewnosc
  slowa: slowa

report_template: |
  ### {url}
  - **Sentyment**: {sentyment}
  - **Pewność**: {pewnosc:.2f}%
  - **Słowa kluczowe**: {slowa}
