data_file: data/smart_home_check.csv
description: Czy firma działa w sektorze smart home / IoT?
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: czy_smart_home
  from: prediction
- field: pewnosc
  from: probability
report_template: '### {url}

  - **Czy smart home / IoT?**: {czy_smart_home}

  - **Pewność**: {pewnosc:.2f}%'
task_name: smart_home_check
type: classification
vectorizer: tfidf
