task_name: smart_home
description: Czy firma działa w sektorze smart home / IoT?
type: classification

input_column: content
output_column: label

model: LogisticRegression
vectorizer: tfidf

data_file: data/smart_home.csv

raw_fields:
  page.url: url
  prediction: czy_smart_home
  probability: pewnosc
  keywords: slowa

template_vars:
  url: url
  czy_smart_home: czy_smart_home
  pewnosc: pewnosc
  slowa: slowa

report_template: |
  ### {url}
  - **Czy smart home / IoT?**: {czy_smart_home}
  - **Pewność**: {pewnosc:.2f}%
  - **Słowa kluczowe**: {slowa}
