data_file: data/b2b_or_b2c.csv
description: 'Klasyfikacja: sprzedaż B2B czy B2C'
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: segment
  from: prediction
- field: pewnosc
  from: probability
report_template: '### {url}

  - **Segment**: {segment}

  - **Pewność**: {pewnosc:.2f}%'
task_name: b2b_or_b2c
type: classification
vectorizer: tfidf
