task_name: b2b_czy_b2c
description: 'Klasyfikacja: sprzedaż B2B czy B2C'
type: classification

input_column: content
output_column: label

model: LogisticRegression
vectorizer: tfidf

data_file: data/b2b_czy_b2c.csv

raw_fields:
  page.url: url
  prediction: segment
  probability: pewnosc
  keywords: slowa

template_vars:
  url: url
  segment: segment
  pewnosc: pewnosc
  slowa: slowa

report_template: |
  ### {url}
  - **Segment**: {segment}
  - **Pewność**: {pewnosc:.2f}%
  - **Słowa kluczowe**: {slowa}
