data_file: data/smart_home_check.csv
description: Detect if a company operates in smart home / IoT sector
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: in_smart_home
  from: prediction
- field: certainty
  from: probability
report_template: '### {url}

  - **Smart Home Related?**: {in_smart_home}

  - **Certainty**: {certainty:.2f}%'
task_name: smart_home_check
type: classification
vectorizer: tfidf
