task_name: linki_spolecznosciowe
description: Czy strona zawiera linki do social mediów?
type: classification

input_column: content
output_column: label

model: LogisticRegression
vectorizer: tfidf

data_file: data/linki_spolecznosciowe.csv

raw_fields:
  page.url: url
  prediction: sociale
  probability: pewnosc
  keywords: slowa

template_vars:
  url: url
  sociale: sociale
  pewnosc: pewnosc
  slowa: slowa

report_template: |
  ### {url}
  - **Social media?**: {sociale}
  - **Pewność**: {pewnosc:.2f}%
  - **Słowa kluczowe**: {slowa}

