data_file: data/social_links.csv
description: Czy strona zawiera linki do social mediów?
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: sociale
  from: prediction
- field: pewnosc
  from: probability
report_template: '### {url}

  - **Social media?**: {sociale}

  - **Pewność**: {pewnosc:.2f}%'
task_name: social_links
type: classification
vectorizer: tfidf
