task_name: potential_client
input_column: content
output_column: label
model: LogisticRegression
vectorizer: tfidf
data_file: data/potential_client.csv

raw_fields:
  page.url: url
  prediction: prediction
  probability: score
  keywords: keywords

template_vars:
  url: url
  Label: prediction
  Score: score
  Keywords: keywords

report_template: |
  ### {url}
  - **Label**: {Label}
  - **Score**: {Score:.1f}%
  - **Keywords**: {Keywords}
