data_file: data/potential_client.csv
description: Predict if a company is a potential client
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: prediction
  from: prediction
- field: confidence
  from: probability
report_template: '### {url}

  - **Prediction**: {prediction}

  - **Confidence**: {confidence:.2f}%'
task_name: potential_client
type: classification
vectorizer: tfidf
