data_file: data/social_links.csv
description: Detect if a page has links to social media
input_column: content
model: LogisticRegression
output_column: label
output_format:
- field: url
  from: page.url
- field: social_media_links
  from: prediction
- field: confidence
  from: probability
report_template: '### {url}

  - **Social Media Links?**: {social_media_links}

  - **Confidence**: {confidence:.2f}%'
task_name: social_links
type: classification
vectorizer: tfidf
